import {
  ClipboardList,
  ClipboardCheck,
  ListChecks,
  FileText,
  Folder,
  Bell,
  Megaphone,
  Flag,
  Star,
  Tag,
  CalendarDays,
  Clock,
  Repeat,
  Wrench,
  Hammer,
  HardHat,
  Plug,
  Lightbulb,
  Zap,
  Thermometer,
  Snowflake,
  Flame,
  Droplet,
  Sparkles,
  SprayCan,
  Trash2,
  Recycle,
  Package,
  Boxes,
  Warehouse,
  Truck,
  ShoppingCart,
  Wallet,
  CreditCard,
  Banknote,
  Coins,
  Calculator,
  Receipt,
  Utensils,
  ChefHat,
  Soup,
  Coffee,
  Wine,
  Beer,
  Martini,
  CupSoda,
  CakeSlice,
  Users,
  UserCheck,
  Phone,
  MessageSquare,
  ShieldCheck,
  Lock,
  Key,
  Camera,
  Siren,
  Monitor,
  Printer,
  Wifi,
  Home,
  Store,
  Building2,
  DoorOpen,
  MapPin,
  Gift,
  Ticket,
  Music,
  Leaf,
  Car,
  Scissors,
  Palette,
  Heart,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  'clipboard-list': ClipboardList,
  'clipboard-check': ClipboardCheck,
  'list-checks': ListChecks,
  'file-text': FileText,
  folder: Folder,
  bell: Bell,
  megaphone: Megaphone,
  flag: Flag,
  star: Star,
  tag: Tag,
  'calendar-days': CalendarDays,
  clock: Clock,
  repeat: Repeat,
  wrench: Wrench,
  hammer: Hammer,
  'hard-hat': HardHat,
  plug: Plug,
  lightbulb: Lightbulb,
  zap: Zap,
  thermometer: Thermometer,
  snowflake: Snowflake,
  flame: Flame,
  droplet: Droplet,
  sparkles: Sparkles,
  'spray-can': SprayCan,
  'trash-2': Trash2,
  recycle: Recycle,
  package: Package,
  boxes: Boxes,
  warehouse: Warehouse,
  truck: Truck,
  'shopping-cart': ShoppingCart,
  wallet: Wallet,
  'credit-card': CreditCard,
  banknote: Banknote,
  coins: Coins,
  calculator: Calculator,
  receipt: Receipt,
  utensils: Utensils,
  'chef-hat': ChefHat,
  soup: Soup,
  coffee: Coffee,
  wine: Wine,
  beer: Beer,
  martini: Martini,
  'cup-soda': CupSoda,
  'cake-slice': CakeSlice,
  users: Users,
  'user-check': UserCheck,
  phone: Phone,
  'message-square': MessageSquare,
  'shield-check': ShieldCheck,
  lock: Lock,
  key: Key,
  camera: Camera,
  siren: Siren,
  monitor: Monitor,
  printer: Printer,
  wifi: Wifi,
  home: Home,
  store: Store,
  'building-2': Building2,
  'door-open': DoorOpen,
  'map-pin': MapPin,
  gift: Gift,
  ticket: Ticket,
  music: Music,
  leaf: Leaf,
  car: Car,
  scissors: Scissors,
  palette: Palette,
  heart: Heart,
};

export function RoomIcon({ name, className }: { name?: string | null; className?: string }) {
  const Icon = ICONS[name ?? ''] ?? ClipboardList;
  return <Icon className={className} />;
}
