import { NextRequest, NextResponse } from 'next/server';
import { createServiceClient } from '@/lib/supabase/server';
import { requireHrManagerForStore, resolveHrScope } from '@/lib/hr/route-auth';
import { logHrAudit } from '@/lib/hr/audit';
import {
  computeDaySummary,
  applyOverride,
  type Punch,
  type DaySummary,
  type TimesheetOverride,
} from '@/lib/hr/time-engine';
import { classifyLeaveEffect, enumerateDates } from '@/lib/hr/leaves';
import { computePayslip, type PayrollInput, type PayslipLine, type PayType, type TaxMode } from '@/lib/hr/payroll';
import { refuseIfConfidentialInScope } from '@/lib/hr/pay-visibility';
import { getHrPolicies } from '@/lib/hr/policy';
import { isUniqueViolation } from '@/lib/hr/db-errors';
import { cycleDates, svPeriodMonth, evalPeriodMonth } from '@/lib/hr/pay-cycle';
import { recomputePoolDeductions } from '@/lib/hr/sc-recompute';
import { businessDateBangkok } from '@/lib/utils/date';

// Last business day that has CLOSED. A rostered day after this is still ahead of us, so it must
// never count as an absence (see time-engine's closedThrough).
const CLOSED_THROUGH = () => businessDateBangkok();

const DEFAULT_WORK_HOURS = 9;

// Cycle date math lives in lib/hr/pay-cycle so the coverage panel measures the same boundaries.
function pad(n: number): string {
  return String(n).padStart(2, '0');
}
function dateRange(from: string, to: string): string[] {
  const out: string[] = [];
  let cur = new Date(`${from}T00:00:00Z`).getTime();
  const end = new Date(`${to}T00:00:00Z`).getTime();
  let guard = 0;
  while (cur <= end && guard < 400) {
    out.push(new Date(cur).toISOString().slice(0, 10));
    cur += 86_400_000;
    guard++;
  }
  return out;
}

interface EmployeeFull {
  payroll_group_id?: string | null;
  id: string;
  profile_id: string;
  rate_satang: number;
  pay_type: string;
  work_hours_per_day: number | null;
  ot_eligible: boolean | null;
  ot_hour_divisor: number | null;
  tax_mode: string;
  sso_enrolled: boolean;
  pvd_enrolled: boolean | null;
  pvd_employee_rate: number | null;
  status: string | null;
  start_date: string | null;
  end_date: string | null;
}
interface TaxAllowanceRow {
  employee_id: string;
  amount_satang: number;
}
interface ScheduleCell {
  user_id: string;
  work_date: string;
  is_day_off: boolean;
  shift: { start_time: string; end_time: string } | null;
}
interface LeaveRow {
  id: string;
  user_id: string;
  leave_type_id: string;
  from_date: string;
  to_date: string;
  cert_path: string | null;
}

interface AssembledLine {
  earnings: PayslipLine[];
  deductions: PayslipLine[];
  gross: number;
  sso: number;
  tax: number;
  totalDed: number;
  net: number;
  workedDays: number;
  attendedDays: number;
}

// POST /api/hr/payruns — generate a payrun for a company (optionally one store) over a pay
// cycle (§A). HR only. For each active employee we assemble the timesheet aggregate, the
// classified approved leaves, recurring items, approved claims, and net Service Charge, then
// run the PURE payroll engine and persist the itemized result. Idempotent per cycle via the
// unique index; re-generating a DRAFT payrun rebuilds its payslips (finalized → 409).
export async function POST(request: NextRequest) {
  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;
  const companyId = typeof body.company_id === 'string' ? body.company_id : '';
  const storeId = typeof body.store_id === 'string' && body.store_id ? body.store_id : null;
  // Which slice of the company's payroll this run covers. null = the default slice (employees with
  // no group), which is what every existing run is — so omitting it keeps today's behaviour.
  const payrollGroupId =
    typeof body.payroll_group_id === 'string' && body.payroll_group_id ? body.payroll_group_id : null;
  const year = Number(body.period_year);
  const month = Number(body.period_month);

  // §P5.5: a store-scoped run is generated by a manager of that store; a company-wide run is full-HR only.
  const auth = await requireHrManagerForStore(storeId);
  if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: auth.status });
  if (!companyId) return NextResponse.json({ error: 'company_id is required' }, { status: 400 });
  if (!Number.isInteger(year) || year < 2000 || year > 2100)
    return NextResponse.json({ error: 'invalid period_year' }, { status: 400 });
  if (!Number.isInteger(month) || month < 1 || month > 12)
    return NextResponse.json({ error: 'invalid period_month' }, { status: 400 });

  const { start, end, payDate } = cycleDates(year, month);
  const service = createServiceClient();

  // Company config for the engine.
  const { data: company, error: companyErr } = await service
    .from('hr_companies')
    .select('id, sso_rate, sso_wage_ceiling_satang, day_divisor, ot_multipliers, wht_rate, sso_prorate')
    .eq('id', companyId)
    .maybeSingle();
  if (companyErr) return NextResponse.json({ error: 'Failed to load company' }, { status: 500 });
  if (!company) return NextResponse.json({ error: 'Company not found' }, { status: 404 });
  const engineCompany = {
    sso_rate: Number(company.sso_rate) || 0.05,
    sso_wage_ceiling_satang: Number(company.sso_wage_ceiling_satang) || 1_750_000,
    day_divisor: Number(company.day_divisor) || 30,
    ot1_multiplier: Number((company.ot_multipliers as { ot1?: number } | null)?.ot1) || 1.5,
    wht_rate: Number(company.wht_rate) || 0.03,
    sso_prorate: company.sso_prorate === true,
  };
  // Group-wide policy knobs (late tiers etc.) — defaults equal the historical constants.
  const policies = await getHrPolicies(service);

  // Active employees of the company (optionally one store).
  const { data: empRows, error: empErr } = await service
    .from('hr_employees')
    .select(
      'id, profile_id, rate_satang, pay_type, work_hours_per_day, ot_eligible, ot_hour_divisor, tax_mode, sso_enrolled, pvd_enrolled, pvd_employee_rate, status, start_date, end_date, payroll_group_id'
    )
    .eq('company_id', companyId)
    // Active/probation staff, PLUS anyone who left on/after the cycle start so a mid-period
    // leaver still gets their final (prorated) pay. Long-ago leavers and future hires are
    // dropped by the employed-window filter below.
    .or(`status.in.(active,probation),end_date.gte.${start}`);
  if (empErr) return NextResponse.json({ error: 'Failed to load employees' }, { status: 500 });
  let employees = ((empRows ?? []) as EmployeeFull[]).filter(
    (e) => (!e.start_date || e.start_date <= end) && (!e.end_date || e.end_date >= start)
  );

  // Keep only this slice. Two runs for one company must not overlap, or someone is paid twice —
  // so a named group takes exactly its members, and the default run takes exactly the ungrouped.
  employees = employees.filter((e) =>
    payrollGroupId ? e.payroll_group_id === payrollGroupId : !e.payroll_group_id
  );

  // A slice containing confidential pay belongs to whoever may see it. Refusing to BUILD the run
  // (rather than building it and blanking the figures) is what makes the split worth having: the
  // restricted HR user never holds a run whose numbers they cannot read, and the run they do hold
  // is complete in itself — no partial totals, nothing to work out by subtraction.
  const groupRefusal = await refuseIfConfidentialInScope(
    service,
    auth.userId,
    employees.map((e) => e.profile_id)
  );
  if (groupRefusal) {
    return NextResponse.json(
      { error: 'งวดนี้มีพนักงานที่ปิดข้อมูลเงินเดือน — ต้องให้ผู้ที่มีสิทธิ์ดูข้อมูลเงินเดือนลับเป็นผู้ทำ' },
      { status: 403 }
    );
  }

  if (storeId) {
    const { data: members, error: memErr } = await service
      .from('user_stores')
      .select('user_id')
      .eq('store_id', storeId);
    if (memErr) return NextResponse.json({ error: 'Failed to load store staff' }, { status: 500 });
    const memberSet = new Set((members ?? []).map((m: { user_id: string }) => m.user_id));
    employees = employees.filter((e) => memberSet.has(e.profile_id));
  }

  // System accounts (print servers, test fixtures) are machines, not payees — drop them even if
  // one was accidentally linked to an hr_employees row. profiles.is_system, not a username prefix.
  if (employees.length) {
    const { data: printerProfiles } = await service
      .from('profiles')
      .select('id')
      .eq('is_system', true)
      .in('id', employees.map((e) => e.profile_id));
    const printerIds = new Set((printerProfiles ?? []).map((r) => r.id as string));
    if (printerIds.size) employees = employees.filter((e) => !printerIds.has(e.profile_id));
  }
  const userIds = employees.map((e) => e.profile_id);

  // Upsert the payrun (draft). A finalized payrun must not be regenerated. The
  // company-wide bucket is the store_id IS NULL row; a store-scoped run matches store_id.
  // Fresh each call (PostgREST builders are single-shot) so we can re-read after a race.
  const findExisting = () => {
    let q = service
      .from('hr_payruns')
      .select('id, status')
      .eq('company_id', companyId)
      .eq('period_year', year)
      .eq('period_month', month);
    q = payrollGroupId ? q.eq('payroll_group_id', payrollGroupId) : q.is('payroll_group_id', null);
    return storeId ? q.eq('store_id', storeId) : q.is('store_id', null);
  };
  const finalizedResponse = () =>
    NextResponse.json({ error: 'Payrun is finalized; reopen before regenerating' }, { status: 409 });

  const { data: existing } = await findExisting().maybeSingle();
  let payrun = existing;
  if (payrun && payrun.status === 'finalized') return finalizedResponse();
  if (!payrun) {
    const { data: created, error: createErr } = await service
      .from('hr_payruns')
      .insert({
        company_id: companyId,
        store_id: storeId,
        payroll_group_id: payrollGroupId,
        period_year: year,
        period_month: month,
        cycle_start: start,
        cycle_end: end,
        pay_date: payDate,
        status: 'draft',
        created_by: auth.userId,
      })
      .select('id, status')
      .single();
    if (createErr) {
      // A concurrent generate (double-click / parallel request) won the insert race on the
      // (company, store, period) unique index. Adopt that row and rebuild it rather than 500ing.
      if (!isUniqueViolation(createErr)) {
        return NextResponse.json({ error: 'Failed to create payrun' }, { status: 500 });
      }
      const { data: raced } = await findExisting().maybeSingle();
      if (!raced) return NextResponse.json({ error: 'Failed to create payrun' }, { status: 500 });
      if (raced.status === 'finalized') return finalizedResponse();
      payrun = raced;
      await service.from('hr_payslips').delete().eq('payrun_id', raced.id);
    } else {
      payrun = created;
    }
  } else {
    // Rebuild: drop prior payslips (cascade clears their lines).
    await service.from('hr_payslips').delete().eq('payrun_id', payrun.id);
  }
  const payrunId = payrun.id;

  if (userIds.length === 0) {
    await logHrAudit(service, {
      actorId: auth.userId, action: 'create', table: 'hr_payruns', recordId: payrunId,
      before: null, after: { period: `${year}-${month}`, employees: 0 }, reason: 'payrun generated (no employees)',
    });
    return NextResponse.json({ data: { id: payrunId, cycle_start: start, cycle_end: end, pay_date: payDate, payslips: 0 } });
  }

  // Bulk-load everything for the cycle in parallel.
  const dates = dateRange(start, end);
  // SV / tip / evaluation pools are THIS month — see svPeriodMonth(): allocated at the start of the
  // month, transferred on the 15th, and reported on this same month's slip. The salary alongside
  // them is period N (26 prev → 25 this). Read paths MUST use the same helper: when they each
  // derived the month, one drifted and a single payslip showed two different SV rounds.
  const svMonth = svPeriodMonth(year, month);

  // Refresh the SC pools this run is about to read, BEFORE reading them.
  //
  // A pool's automatic deductions (leave, absence, warnings, carry) are only rebuilt when HR saves
  // allocations, presses Recompute, or finalizes. Correct a timesheet after that and the pool keeps
  // the figures it had: one August run carried "ขาดงาน 3 วัน" in the SV while the slip beside it
  // docked 16, because the timesheet had been reset in between (client report 2026-08-20). HR was
  // left having to remember which button to press in which order.
  //
  // Doing it here rather than on every timesheet edit is deliberate: a recompute costs a query per
  // source per allocation, and the timesheet is edited dozens of times a day — the bulk-backfill
  // tool stamps a whole grid at once. This runs once per generation, at the moment the numbers have
  // to be right. Only DRAFT pools are touched (recompute no-ops on a finalized one) and only their
  // auto lines are rebuilt, so anything HR entered by hand survives.
  //
  // A pool that fails to refresh does not sink the run — the payslips are the point — but it is
  // named in the response instead of passing for a silent success.
  const scRecomputed: string[] = [];
  const scRecomputeFailed: string[] = [];
  {
    const { data: poolRows } = await service
      .from('hr_sc_allocations')
      .select('pool_id, pool:hr_sc_pools!inner(id, store_id, period_month, status)')
      .in('user_id', userIds)
      .eq('pool.period_month', svMonth)
      .eq('pool.status', 'draft');
    const poolIds = [...new Set(((poolRows ?? []) as unknown as { pool_id: string }[]).map((r) => r.pool_id))];
    for (const poolId of poolIds) {
      try {
        await recomputePoolDeductions(service, poolId, auth.userId);
        scRecomputed.push(poolId);
      } catch {
        scRecomputeFailed.push(poolId);
      }
    }
    if (scRecomputed.length > 0 || scRecomputeFailed.length > 0) {
      await logHrAudit(service, {
        actorId: auth.userId,
        action: 'update',
        table: 'hr_sc_pools',
        recordId: payrunId,
        after: { period_month: svMonth, recomputed: scRecomputed, failed: scRecomputeFailed },
        reason: `SC pools refreshed by payrun generation ${year}-${pad(month)}`,
      });
    }
  }

  const [scheduleRes, attendanceRes, overridesRes, leavesRes, leaveTypesRes, recurringRes, scRes, claimsRes, taxAllowRes, tipRes, evalBonusRes] =
    await Promise.all([
      service
        .from('hr_schedule')
        .select('user_id, work_date, is_day_off, shift:hr_shift_templates(start_time, end_time)')
        .in('user_id', userIds)
        .gte('work_date', start)
        .lte('work_date', end),
      service
        .from('hr_attendance')
        .select('user_id, type, ts, business_date')
        .in('user_id', userIds)
        .gte('business_date', start)
        .lte('business_date', end)
        // Exclude punches HR has rejected (out-of-geofence / VPN-suspect). Matches the HR
        // timesheet, which never counts a rejected punch toward pay; NULL review_status
        // (an ordinary un-flagged punch) is kept.
        .or('review_status.is.null,review_status.neq.rejected'),
      service
        .from('hr_timesheet_overrides')
        .select('user_id, business_date, worked_min, late_min, ot_min, absent, reason')
        .in('user_id', userIds)
        .gte('business_date', start)
        .lte('business_date', end),
      service
        .from('hr_leaves')
        .select('id, user_id, leave_type_id, from_date, to_date, cert_path')
        .in('user_id', userIds)
        .eq('status', 'approved')
        .lte('from_date', end)
        .gte('to_date', start),
      service.from('hr_leave_types').select('id, code, paid, paid_with_cert, deduct_sc, deduct_travel'),
      // Recurring items: only THIS run's employees (was an unscoped all-tenant scan), and only rows
      // whose period window covers this payrun period. Window sides are 'YYYY-MM' text (00162);
      // null start = since forever, null end = perpetual — expiry is enforced here, not by memory.
      service
        .from('hr_employee_recurring')
        .select('employee_id, kind, code, label, amount_satang')
        .eq('active', true)
        .in('employee_id', employees.map((e) => e.id))
        .or(`start_period.is.null,start_period.lte.${year}-${pad(month)}`)
        .or(`end_period.is.null,end_period.gte.${year}-${pad(month)}`),
      // Net SC for THIS month's pool — allocated at the start of it, transferred on the 15th.
      service
        .from('hr_sc_allocations')
        .select('user_id, allocated_satang, pool:hr_sc_pools!inner(period_month), hr_sc_deductions(amount_satang)')
        .eq('pool.period_month', svMonth),
      service
        .from('hr_claims')
        .select('id, user_id, amount_satang, description')
        .in('user_id', userIds)
        .eq('status', 'approved')
        .is('payslip_earning_id', null),
      // ล.ย.01 tax allowances active for THIS tax year (Gregorian year of the cycle end).
      service
        .from('hr_tax_allowances')
        .select('employee_id, amount_satang')
        .eq('tax_year', year)
        .eq('active', true),
      // Net Tip pool for THIS month — same mechanism/timing as SC.
      service
        .from('hr_tip_allocations')
        .select('user_id, allocated_satang, pool:hr_tip_pools!inner(period_month), hr_tip_deductions(amount_satang)')
        .eq('pool.period_month', svMonth),
      // POSITIVE eval payouts (bonuses) for the PREVIOUS month's period — the same evaluation whose
      // negative side docks this month's SC pool (apply-sc / scPoolMonthForEvent), so both halves of one
      // evaluation land on one slip. Negative payouts are not read here.
      service
        .from('hr_eval_payouts')
        .select('id, amount_satang, result:hr_eval_results!inner(employee_id, period:hr_eval_periods!inner(period_month))')
        .eq('status', 'approved')
        .gt('amount_satang', 0)
        .eq('result.period.period_month', evalPeriodMonth(year, month)),
    ]);
  const anyErr =
    scheduleRes.error || attendanceRes.error || overridesRes.error || leavesRes.error ||
    leaveTypesRes.error || recurringRes.error || scRes.error || claimsRes.error || taxAllowRes.error || tipRes.error || evalBonusRes.error;
  if (anyErr) return NextResponse.json({ error: 'Failed to load payroll inputs' }, { status: 500 });

  // Index the bulk data.
  const schedByCell = new Map<string, ScheduleCell>(
    ((scheduleRes.data ?? []) as unknown as ScheduleCell[]).map((s) => [`${s.user_id}|${s.work_date}`, s])
  );
  const punchesByCell = new Map<string, Punch[]>();
  for (const a of (attendanceRes.data ?? []) as { user_id: string; type: Punch['type']; ts: string; business_date: string }[]) {
    const key = `${a.user_id}|${a.business_date}`;
    const list = punchesByCell.get(key) ?? [];
    list.push({ type: a.type, ts: a.ts });
    punchesByCell.set(key, list);
  }
  const overrideByCell = new Map<string, TimesheetOverride>(
    ((overridesRes.data ?? []) as { user_id: string; business_date: string; worked_min: number | null; late_min: number | null; ot_min: number | null; absent: boolean | null; reason: string | null }[]).map((o) => [
      `${o.user_id}|${o.business_date}`,
      { worked_min: o.worked_min, late_min: o.late_min, ot_min: o.ot_min, absent: o.absent, reason: o.reason },
    ])
  );
  const leaveTypeById = new Map(
    ((leaveTypesRes.data ?? []) as { id: string; code: string; paid: boolean; paid_with_cert: boolean; deduct_sc: boolean; deduct_travel: boolean }[]).map((t) => [t.id, t])
  );
  const leavesByUser = new Map<string, LeaveRow[]>();
  for (const lv of (leavesRes.data ?? []) as LeaveRow[]) {
    const list = leavesByUser.get(lv.user_id) ?? [];
    list.push(lv);
    leavesByUser.set(lv.user_id, list);
  }
  // ล.ย.01 tax allowances: sum active annual amounts per employee (satang → baht for the engine).
  const taxAllowBahtByEmp = new Map<string, number>();
  for (const a of (taxAllowRes.data ?? []) as TaxAllowanceRow[]) {
    taxAllowBahtByEmp.set(a.employee_id, (taxAllowBahtByEmp.get(a.employee_id) ?? 0) + a.amount_satang);
  }
  const recurringByEmp = new Map<string, { kind: string; code: string; label: string; amount_satang: number }[]>();
  for (const r of (recurringRes.data ?? []) as { employee_id: string; kind: string; code: string; label: string; amount_satang: number }[]) {
    const list = recurringByEmp.get(r.employee_id) ?? [];
    list.push(r);
    recurringByEmp.set(r.employee_id, list);
  }
  // net SC per user = allocated − Σ deductions, floored at 0 (P4.1).
  const scNetByUser = new Map<string, number>();
  for (const a of (scRes.data ?? []) as { user_id: string; allocated_satang: number; hr_sc_deductions: { amount_satang: number }[] }[]) {
    const ded = (a.hr_sc_deductions ?? []).reduce((s, d) => s + Math.max(0, d.amount_satang), 0);
    const net = Math.max(0, a.allocated_satang - ded);
    scNetByUser.set(a.user_id, (scNetByUser.get(a.user_id) ?? 0) + net);
  }
  const tipNetByUser = new Map<string, number>();
  for (const a of (tipRes.data ?? []) as { user_id: string; allocated_satang: number; hr_tip_deductions: { amount_satang: number }[] }[]) {
    const ded = (a.hr_tip_deductions ?? []).reduce((s, d) => s + Math.max(0, d.amount_satang), 0);
    const net = Math.max(0, a.allocated_satang - ded);
    tipNetByUser.set(a.user_id, (tipNetByUser.get(a.user_id) ?? 0) + net);
  }
  const claimsByUser = new Map<string, { id: string; amount_satang: number; description: string }[]>();
  for (const c of (claimsRes.data ?? []) as { id: string; user_id: string; amount_satang: number; description: string }[]) {
    const list = claimsByUser.get(c.user_id) ?? [];
    list.push(c);
    claimsByUser.set(c.user_id, list);
  }
  // Positive eval payouts → eval_bonus earning, keyed by the result's employee (a profile id).
  const evalBonusByUser = new Map<string, { id: string; amount_satang: number }[]>();
  for (const p of (evalBonusRes.data ?? []) as unknown as { id: string; amount_satang: number; result: { employee_id: string } | null }[]) {
    const uid = p.result?.employee_id;
    if (!uid) continue;
    const list = evalBonusByUser.get(uid) ?? [];
    list.push({ id: p.id, amount_satang: p.amount_satang });
    evalBonusByUser.set(uid, list);
  }

  // Accounting-office tax overrides for this payrun — keyed by profile so a draft REGENERATE
  // re-applies them (the whole point of storing them off the payslip row).
  const { data: taxOvrRows, error: taxOvrErr } = await service
    .from('hr_payslip_tax_overrides')
    .select('profile_id, tax_satang')
    .eq('payrun_id', payrunId);
  if (taxOvrErr) return NextResponse.json({ error: 'Failed to load tax overrides' }, { status: 500 });
  const taxOverrideByUser = new Map<string, number>(
    ((taxOvrRows ?? []) as { profile_id: string; tax_satang: number }[]).map((r) => [r.profile_id, Number(r.tax_satang)])
  );

  // HR-entered one-time bonuses for this payrun — keyed by profile so a draft REGENERATE
  // re-applies them (stored off the payslip row, same pattern as tax overrides).
  const { data: bonusRows, error: bonusErr } = await service
    .from('hr_payslip_bonuses')
    .select('profile_id, amount_satang, label')
    .eq('payrun_id', payrunId);
  if (bonusErr) return NextResponse.json({ error: 'Failed to load bonuses' }, { status: 500 });
  const bonusByUser = new Map<string, { amount_satang: number; label: string | null }[]>();
  for (const b of (bonusRows ?? []) as { profile_id: string; amount_satang: number; label: string | null }[]) {
    const list = bonusByUser.get(b.profile_id) ?? [];
    list.push({ amount_satang: b.amount_satang, label: b.label });
    bonusByUser.set(b.profile_id, list);
  }

  // One-off adjustment lines for this payrun (hr_payrun_adjustments) — the third durable
  // survivor keyed by (payrun, profile); each row re-posts as an 'adjustment' line every rebuild.
  const { data: adjRows, error: adjErr } = await service
    .from('hr_payrun_adjustments')
    .select('id, profile_id, kind, label, amount_satang')
    .eq('payrun_id', payrunId);
  if (adjErr) return NextResponse.json({ error: 'Failed to load adjustments' }, { status: 500 });
  const adjByUser = new Map<string, { id: string; kind: string; label: string; amount_satang: number }[]>();
  for (const a of (adjRows ?? []) as { id: string; profile_id: string; kind: string; label: string; amount_satang: number }[]) {
    const list = adjByUser.get(a.profile_id) ?? [];
    list.push(a);
    adjByUser.set(a.profile_id, list);
  }

  // Per-employee: assemble → compute → collect for insert.
  const assembled: { emp: EmployeeFull; slip: AssembledLine; claimIds: string[] }[] = [];
  for (const emp of employees) {
    const uid = emp.profile_id;
    const workHours = emp.work_hours_per_day ?? DEFAULT_WORK_HOURS;
    const otEligible = emp.ot_eligible ?? false;

    // Timesheet days over the cycle.
    const days: DaySummary[] = dates.map((date) => {
      const cell = schedByCell.get(`${uid}|${date}`);
      const derived = computeDaySummary({
        businessDate: date,
        shift: cell?.shift ?? null,
        isDayOff: cell?.is_day_off ?? false,
        hasSchedule: !!cell,
        punches: punchesByCell.get(`${uid}|${date}`) ?? [],
        workHoursPerDay: workHours,
        otEligible,
        closedThrough: CLOSED_THROUGH(),
      });
      return applyOverride(derived, overrideByCell.get(`${uid}|${date}`));
    });

    // Employed window inside the cycle → mid-period hire/leave proration for full_monthly.
    const empStart = emp.start_date && emp.start_date > start ? emp.start_date : start;
    const empEnd = emp.end_date && emp.end_date < end ? emp.end_date : end;
    const isPartialPeriod =
      (!!emp.start_date && emp.start_date > start) || (!!emp.end_date && emp.end_date < end);
    const inWindow = (d: string) => d >= empStart && d <= empEnd;
    // prorate_days: null when employed the whole cycle (→ full base, unchanged). Otherwise the
    // employed-day count by the configured basis. 'scheduled' treats no-schedule days as work
    // days and only drops explicit roster day-offs (matches the leave-docking convention).
    let prorateDays: number | null = null;
    if (isPartialPeriod) {
      prorateDays =
        policies.prorate_basis === 'scheduled'
          ? dates.filter(
              (d) => inWindow(d) && schedByCell.get(`${uid}|${d}`)?.is_day_off !== true
            ).length
          : dateRange(empStart, empEnd).length; // calendar days employed
    }

    // A worked day = a real punch OR an HR override that credits worked minutes (matching
    // time-engine's sumDays). Counting only `first_in` underpaid pt_daily/pt_monthly staff for
    // days HR back-filled via hr_timesheet_overrides without a punch.
    const workedDays = days.filter((d) => d.first_in || (d.worked_min ?? 0) > 0).length;
    const ptHours = days.reduce((s, d) => s + (d.worked_min ?? 0), 0) / 60;
    const otMinutes = days.reduce((s, d) => s + d.ot_min, 0);

    // Classified leaves overlapping the cycle → salary/travel day counts + covered dates.
    const leaveCovered = new Set<string>();
    const engineLeaves = (leavesByUser.get(uid) ?? []).map((lv) => {
      const t = leaveTypeById.get(lv.leave_type_id);
      const effect = classifyLeaveEffect(
        {
          paid: t?.paid ?? false,
          paid_with_cert: t?.paid_with_cert ?? false,
          deduct_sc: t?.deduct_sc ?? true,
          deduct_travel: t?.deduct_travel ?? true,
        },
        !!lv.cert_path
      );
      const from = lv.from_date < start ? start : lv.from_date;
      const to = lv.to_date > end ? end : lv.to_date;
      for (const d of enumerateDates(from, to)) leaveCovered.add(d);
      // A leave day only docks salary/travel if the employee was rostered to work it: exclude
      // the employee's scheduled weekly day-offs (is_day_off) — the roster is now the only source of
      // leave-approval timesheet path. Dates with no schedule row yet still count (can't assume a
      // future day off). Previously this counted every calendar day → over-docked a leave that
      // spanned a day off (e.g. 7 days docked instead of 6).
      const daysInCycle = enumerateDates(from, to).filter(
        (d) => inWindow(d) && schedByCell.get(`${uid}|${d}`)?.is_day_off !== true
      ).length;
      return {
        leave_id: lv.id,
        label: t?.code ?? 'leave',
        salary_days: effect.deductSalary ? daysInCycle : 0,
        travel_days: effect.deductTravel ? daysInCycle : 0,
      };
    });

    // A late fine only applies to a day the person was actually due at work. Someone who taps in
    // on a rostered day off, or on a day an approved leave already covers, is not "late" for a
    // shift they did not owe — payroll was fining both (owner decision 2026-08-18).
    const lateOccurrences = days
      .filter((d) => !d.is_day_off && !leaveCovered.has(d.business_date))
      .map((d) => d.late_min ?? 0)
      .filter((m) => m > 0);

    // Unauthorized absence = absent timesheet days NOT covered by an approved leave, and only
    // within the employed window (days before hire / after leave never count as absent).
    const unauthorizedAbsentDays = days.filter(
      (d) => d.absent && !leaveCovered.has(d.business_date) && inWindow(d.business_date)
    ).length;

    // Recorded days that were real attendance. workedDays counts any day with a time record, which
    // includes a day someone punched while on approved leave — correct for pay, misleading on a
    // slip (7 recorded days where 5 were attendance and 2 were leave she also clocked on). Split
    // here, off the same `days` and leaveCovered the absence count uses, so the rule stays in one
    // place instead of being restated wherever the number is shown.
    const attendedDays = days.filter(
      (d) => (d.first_in || (d.worked_min ?? 0) > 0) && !leaveCovered.has(d.business_date)
    ).length;

    const recurring = recurringByEmp.get(emp.id) ?? [];
    const allowances = recurring
      .filter((r) => r.kind === 'earning')
      .map((r) => ({ code: r.code, label: r.label, amount_satang: r.amount_satang }));
    const recurringDeductions = recurring
      .filter((r) => r.kind === 'deduction')
      .map((r) => ({ type: mapDeductionType(r.code), label: r.label, amount_satang: r.amount_satang }));

    const claimList = claimsByUser.get(uid) ?? [];
    const evalBonusList = evalBonusByUser.get(uid) ?? [];
    const adjList = adjByUser.get(uid) ?? [];
    const extraEarnings = [
      ...claimList.map((c) => ({
        type: 'claim' as const, label: c.description || 'claim', amount_satang: c.amount_satang, ref: c.id,
      })),
      ...evalBonusList.map((b) => ({
        type: 'eval_bonus' as const, label: 'eval_bonus', amount_satang: b.amount_satang, ref: b.id,
      })),
      ...(bonusByUser.get(uid) ?? []).map((b) => ({
        type: 'bonus' as const, label: b.label || 'bonus', amount_satang: b.amount_satang, ref: null,
      })),
      ...adjList
        .filter((a) => a.kind === 'earning')
        .map((a) => ({ type: 'adjustment' as const, label: a.label, amount_satang: a.amount_satang, ref: a.id })),
    ];
    const extraDeductions = adjList
      .filter((a) => a.kind === 'deduction')
      .map((a) => ({ type: 'adjustment' as const, label: a.label, amount_satang: a.amount_satang, ref: a.id }));

    const input: PayrollInput = {
      employee: {
        rate_satang: emp.rate_satang,
        pay_type: (emp.pay_type as PayType) || 'full_monthly',
        ot_eligible: otEligible,
        ot_hour_divisor: emp.ot_hour_divisor ?? workHours,
        tax_mode: (emp.tax_mode as TaxMode) || 'progressive',
        sso_enrolled: emp.sso_enrolled,
        tax_allowances_baht: (taxAllowBahtByEmp.get(emp.id) ?? 0) / 100,
        pvd_enrolled: emp.pvd_enrolled ?? false,
        pvd_employee_rate: emp.pvd_employee_rate ?? 0,
      },
      company: engineCompany,
      timesheet: {
        worked_days: workedDays,
        pt_hours: ptHours,
        ot_minutes_eligible: otMinutes,
        late_minutes_per_occurrence: lateOccurrences,
        unauthorized_absent_days: unauthorizedAbsentDays,
        prorate_days: prorateDays,
      },
      leaves: engineLeaves,
      allowances,
      recurringDeductions,
      extraEarnings,
      extraDeductions,
      scNetSatang: scNetByUser.get(uid) ?? 0,
      tipNetSatang: tipNetByUser.get(uid) ?? 0,
      lateTiers: policies.late_tiers,
      taxOverrideSatang: taxOverrideByUser.get(uid) ?? null,
    };
    const slip = computePayslip(input);
    assembled.push({
      emp,
      slip: {
        earnings: slip.earnings, deductions: slip.deductions, gross: slip.gross_satang, sso: slip.sso_satang,
        tax: slip.tax_satang, totalDed: slip.total_deduction_satang, net: slip.net_satang, workedDays, attendedDays,
      },
      claimIds: claimList.map((c) => c.id),
    });
  }

  // Persist per employee: payslip + earning/deduction lines; link approved claims.
  let created = 0;
  for (const { emp, slip } of assembled) {
    const { data: ps, error: psErr } = await service
      .from('hr_payslips')
      .insert({
        payrun_id: payrunId,
        user_id: emp.profile_id,
        employee_id: emp.id,
        rate_satang: emp.rate_satang,
        pay_type: emp.pay_type,
        tax_mode: emp.tax_mode,
        worked_days: slip.workedDays,
        attended_days: slip.attendedDays,
        gross_satang: slip.gross,
        sso_satang: slip.sso,
        tax_satang: slip.tax,
        total_deduction_satang: slip.totalDed,
        net_satang: slip.net,
      })
      .select('id')
      .single();
    if (psErr || !ps) continue;

    // Persist itemized lines. A failing line insert must NOT be swallowed: a CHECK/enum gap would
    // otherwise drop the whole line set and leave a payslip whose cached totals disagree with its
    // (empty) itemization — an invisible payroll-correctness defect. Fail loudly instead.
    if (slip.earnings.length) {
      const { error: earnErr } = await service.from('hr_payslip_earnings').insert(
        slip.earnings.map((l, i) => ({ payslip_id: ps.id, type: l.type, label: l.label, amount_satang: l.amount_satang, ref: l.ref ?? null, sort: i }))
      );
      if (earnErr) return NextResponse.json({ error: 'Failed to persist payslip earning lines' }, { status: 500 });
    }
    if (slip.deductions.length) {
      const { error: dedErr } = await service.from('hr_payslip_deductions').insert(
        slip.deductions.map((l, i) => ({ payslip_id: ps.id, type: l.type, label: l.label, amount_satang: l.amount_satang, ref: l.ref ?? null, created_by: auth.userId, sort: i }))
      );
      if (dedErr) return NextResponse.json({ error: 'Failed to persist payslip deduction lines' }, { status: 500 });
    }
    // NOTE: approved claims are NOT marked paid here. A payrun POST always produces a DRAFT, and a
    // draft can be regenerated or abandoned — marking claims 'paid' on generation permanently lost
    // the reimbursement if the draft was discarded. Claims stay 'approved' (re-picked on every
    // regenerate via the payslip_earning_id-null filter) and are marked paid at FINALIZE, keyed by
    // the claim id carried in each claim earning's `ref`.
    created++;
  }

  await logHrAudit(service, {
    actorId: auth.userId, action: 'create', table: 'hr_payruns', recordId: payrunId,
    before: null, after: { period: `${year}-${pad(month)}`, cycle: `${start}..${end}`, employees: created },
    reason: 'payrun generated',
  });

  return NextResponse.json({
    data: {
      id: payrunId,
      cycle_start: start,
      cycle_end: end,
      pay_date: payDate,
      payslips: created,
      // Which SC pools this generation refreshed on the way — the run edits them, so it says so.
      sc_pools_recomputed: scRecomputed.length,
      sc_pools_failed: scRecomputeFailed,
    },
  });
}

function mapDeductionType(code: string): 'student_loan' | 'advance' | 'guarantee' | 'loan' | 'other' {
  if (code === 'student_loan' || code === 'advance' || code === 'guarantee' || code === 'loan') return code;
  return 'other';
}

// GET /api/hr/payruns?company_id? — list payruns (HR only), newest first.
export async function GET(request: NextRequest) {
  // §P5.5: company-wide HR sees every payrun; a store-scoped manager sees only their stores' runs.
  const scope = await resolveHrScope();
  if (!scope.ok) return NextResponse.json({ error: scope.error }, { status: scope.status });

  const companyId = request.nextUrl.searchParams.get('company_id');
  const service = createServiceClient();
  let q = service
    .from('hr_payruns')
    .select('id, company_id, store_id, payroll_group_id, period_year, period_month, cycle_start, cycle_end, pay_date, status, finalized_at, created_at, payroll_group:hr_payroll_groups(id, name)')
    .order('period_year', { ascending: false })
    .order('period_month', { ascending: false });
  if (companyId) q = q.eq('company_id', companyId);
  if (scope.storeIds) q = q.in('store_id', scope.storeIds); // scoped manager: only their stores' (store-scoped) runs
  const { data, error } = await q;
  if (error) return NextResponse.json({ error: 'Failed to load payruns' }, { status: 500 });
  return NextResponse.json({ data: data ?? [] });
}
