/**
 * Screenshot URL registry for the in-app user manual (/guide).
 *
 * Key   = image file name referenced by <ManualImg name="..."> in guide sections
 *         (the same names listed in docs/hr/manualphoto.md).
 * Value = public URL of the uploaded screenshot (e.g. Supabase Storage public URL).
 *
 * An empty string means "not uploaded yet" — the manual renders a dashed
 * placeholder box with the file name so anyone can see which shot is missing.
 * To publish a screenshot: upload it, then paste the URL here. No other edit needed.
 */
export const MANUAL_IMAGES: Record<string, string> = {
  // ── HR — ภาพรวม & แดชบอร์ด ──
  "hr-home-01-module-tile.png": '',
  "hr-home-02-hub.png": '',
  "hr-dashboard-01-overview.png": '',
  "hr-dashboard-02-today-charts.png": '',
  "hr-dashboard-03-month-section.png": '',
  "hr-dashboard-04-alerts.png": '',
  // ── HR — พนักงาน & ยืนยันตัวตน ──
  "hr-employees-01-overview.png": '',
  "hr-employees-02-create-modal.png": '',
  "hr-employees-03-temp-password.png": '',
  "hr-employees-04-transfer-modal.png": '',
  "hr-employees-05-history-modal.png": '',
  "hr-identity-claims-01-overview.png": '',
  "hr-identity-claims-02-reject-dialog.png": '',
  "hr-identity-claims-03-unclaimed-list.png": '',
  // ── HR — โครงสร้างองค์กร & กติกา ──
  "hr-org-01-overview.png": '',
  "hr-org-02-inline-edit.png": '',
  "hr-org-03-departments-tab.png": '',
  "hr-org-chart-01-overview.png": '',
  "hr-org-chart-02-node-card.png": '',
  "hr-org-chart-03-search.png": '',
  "hr-companies-01-overview.png": '',
  "hr-companies-02-edit-modal.png": '',
  "hr-policy-settings-01-overview.png": '',
  "hr-policy-settings-02-announce-mode.png": '',
  "hr-policy-settings-03-reason-dialog.png": '',
  // ── HR — ลงเวลา & ตารางงาน ──
  "hr-attendance-01-overview.png": '',
  "hr-attendance-02-table-badges.png": '',
  "hr-attendance-03-suspect-filter.png": '',
  "hr-locations-01-overview.png": '',
  "hr-locations-02-use-my-location.png": '',
  "hr-locations-03-branch-set.png": '',
  "hr-schedule-01-overview.png": '',
  "hr-schedule-02-add-shift.png": '',
  "hr-schedule-03-cell-editor.png": '',
  "hr-schedule-04-balance.png": '',
  "hr-timesheet-01-overview.png": '',
  "hr-timesheet-02-day-table.png": '',
  "hr-timesheet-03-edit-modal.png": '',
  "hr-timesheet-04-clear-override.png": '',
  // ── HR — การลา & คำขอเวลา ──
  "hr-leaves-01-overview.png": '',
  "hr-leaves-02-reject-note.png": '',
  "hr-leave-types-01-overview.png": '',
  "hr-leave-types-02-holidays-tab.png": '',
  "hr-leave-types-03-leave-type-modal.png": '',
  "hr-leave-types-04-holiday-modal.png": '',
  "hr-requests-01-overview.png": '',
  "hr-requests-02-approve-buttons.png": '',
  "hr-requests-03-reject-note.png": '',
  "hr-requests-04-attendance-applied.png": '',
  "hr-swaps-01-overview.png": '',
  "hr-swaps-02-reject-note.png": '',
  "hr-swaps-03-acknowledge.png": '',
  // ── HR — ใบเตือน เบิกจ่าย & พ้นสภาพ ──
  "hr-warnings-01-overview.png": '',
  "hr-warnings-02-issue-modal.png": '',
  "hr-warnings-03-sign-modal.png": '',
  "hr-warnings-04-void-modal.png": '',
  "hr-claims-01-overview.png": '',
  "hr-claims-02-pending-card.png": '',
  "hr-claims-03-reject-note.png": '',
  "hr-profile-requests-01-overview.png": '',
  "hr-profile-requests-02-pending-card.png": '',
  "hr-profile-requests-03-reject-note.png": '',
  "hr-offboarding-01-overview.png": '',
  "hr-offboarding-02-initiate-modal.png": '',
  "hr-offboarding-03-detail-assets.png": '',
  "hr-offboarding-04-sign-modal.png": '',
  "hr-offboarding-05-print-form.png": '',
  // ── HR — เงินเดือน ──
  "hr-payroll-01-overview.png": '',
  "hr-payroll-02-print-queue.png": '',
  "hr-payroll-03-slip-modal.png": '',
  "hr-payroll-04-review-link.png": '',
  "hr-payroll-compare-01-overview.png": '',
  "hr-payroll-compare-02-selectors.png": '',
  "hr-payroll-compare-03-result.png": '',
  // ── HR — เอกสาร & หนังสือรับรอง ──
  "hr-document-requests-01-overview.png": '',
  "hr-document-requests-02-attach-file.png": '',
  "hr-document-requests-03-reject-reason.png": '',
  "hr-certificates-01-overview.png": '',
  "hr-certificates-02-pdf-output.png": '',
  // ── HR — เซอร์วิสชาร์จ & ทิป ──
  "hr-service-charge-01-overview.png": '',
  "hr-service-charge-02-row-expanded.png": '',
  "hr-service-charge-03-manual-deduction-modal.png": '',
  "hr-service-charge-04-finalize-confirm.png": '',
  "hr-tip-pool-01-overview.png": '',
  "hr-tip-pool-02-deduction-row.png": '',
  "hr-tip-pool-03-finalize-confirm.png": '',
  // ── HR — ประเมินผล ──
  "hr-evaluation-01-overview.png": '',
  "hr-evaluation-02-assignments.png": '',
  "hr-evaluation-03-results.png": '',
  "hr-evaluation-04-payout-rule.png": '',
  "hr-evaluation-05-payouts.png": '',
  "hr-evaluation-detail-01-overview.png": '',
  "hr-evaluation-detail-02-assignments.png": '',
  "hr-evaluation-detail-03-results.png": '',
  "hr-evaluation-detail-04-payout-rule.png": '',
  "hr-evaluation-detail-05-approve-apply.png": '',
  // ── HR — ทรัพย์สิน นโยบาย & ประกาศ ──
  "hr-assets-01-overview.png": '',
  "hr-assets-02-edit-modal.png": '',
  "hr-policies-01-overview.png": '',
  "hr-policies-02-editor-modal.png": '',
  "hr-policies-03-acks-modal.png": '',
  "hr-announcements-01-overview.png": '',
  "hr-announcements-02-editor-modal.png": '',
  "hr-announcements-03-scope-select.png": '',
  "hr-announcements-04-receipts-modal.png": '',
  // ── HR — ตรวจสอบ & รายงาน ──
  "hr-audit-01-overview.png": '',
  "hr-audit-02-filters.png": '',
  "hr-audit-03-table.png": '',
  "hr-reports-01-overview.png": '',
  "hr-reports-02-pnd1-csv.png": '',
  "hr-reports-03-cert50twi-pdf.png": '',
  // ── HR — ฝั่งพนักงาน (ของฉัน) ──
  "me-time-01-overview.png": '',
  "me-time-02-checkin.png": '',
  "me-time-03-schedule.png": '',
  "me-time-04-timesheet.png": '',
  "me-requests-01-overview.png": '',
  "me-requests-02-leave-form.png": '',
  "me-requests-03-ot-form.png": '',
  "me-requests-04-attendance-form.png": '',
  "me-requests-05-swap-form.png": '',
  "me-money-docs-01-hub.png": '',
  "me-money-docs-02-payslips.png": '',
  "me-money-docs-03-doc-request.png": '',
  "me-money-docs-04-claims.png": '',
  "me-other-01-profile.png": '',
  "me-other-02-warnings.png": '',
  "me-other-03-evaluations.png": '',
  "me-other-04-policies.png": '',
  "me-other-05-offboarding.png": '',
};
